/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jt.givi.gui;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author superman
 */
public class LogoPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogoPanel
     */
    public LogoPanel() {
        initComponents();
        try {
            InputStream imageStream = LogoPanel.class.getResourceAsStream("/logo.jpg");
            BufferedImage myPicture = ImageIO.read(imageStream);
            JLabel picLabel = new JLabel(new ImageIcon(myPicture));
            picLabel.setBackground(Color.WHITE);
            logoPanel.add(picLabel);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        wordingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1360, 100));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {263, 1103};
        setLayout(layout);

        logoPanel.setOpaque(false);
        add(logoPanel, new java.awt.GridBagConstraints());

        wordingPanel.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 76)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Monitoring System");
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        wordingPanel.add(jLabel1);

        add(wordingPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel wordingPanel;
    // End of variables declaration//GEN-END:variables
}
